import type { Metadata } from "next";
import React from 'react'
import { VRegistry } from 'vyakui-react';
import { fontBody, fontHeading } from '@/fonts';
import "vyakui-react/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontHeading.variable} ${fontBody.variable}`} style={{backgroundColor: "rgba(0, 0, 0, 1)"}}>
      <VRegistry>
        {children}
      </VRegistry>
      </body>
    </html>
  );
}
