import { Footer, Header, sizeStyle } from '@/components'
import type { Metadata } from "next";
import React from 'react'
import { color, getRem, VFlex, VRegistry } from '@/vyakui-react';
import { fontBody, fontHeading } from '@/fonts';
import "@/vyakui-react/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontHeading.variable} ${fontBody.variable}`} style={{backgroundColor: color.gray5, color: color.gray1}}>
      <VRegistry>
        <Header/>
        <VFlex
          gap={64}
          as={"main"}
          direction={"column"}
          vStyle={{
            ...sizeStyle,
            marginTop: getRem(80)
          }}
        >
          {children}
          <Footer/>
        </VFlex>
      </VRegistry>
      </body>
    </html>
  );
}
